server:
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

logging:
  level:
    web: INFO

spring:
  beaninfo:
    ignore: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
  flyway:
    enabled: true
    table: migration
    create-schemas: true
    locations: classpath:db/migration/H2
  h2:
    console:
      enabled: false
  jpa:
    open-in-view: false
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
