server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: true

logging:
  level:
    web: INFO

spring:
  application:
    name: library-service
  beaninfo:
    ignore: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?stringtype=unspecified
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  flyway:
    enabled: true
    table: migration
    create-schemas: true
    locations: classpath:db/migration/PostgreSQL
  h2:
    console:
      enabled: false
  jpa:
    open-in-view: false
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
